### ISSUE TITLE
Spruce up UI for curriculum app

### ISSUE THREAD

**Issue by jeffreywescott** [GuildCrafts/curriculum#76] opened 2017-07-10 19:07 UTC
(merged two stories to create this one)

---

From [ch3847](https://app.clubhouse.io/learnersguild/story/3847)

Some simple design tweaks we could do:

- Use Material UI
- Convert to Guild colors, typefaces
- Use style idioms for buttons, layout, etc.

---

From [ch3403](https://app.clubhouse.io/learnersguild/story/3403)

### colors

We need to ensure that the branding (colors, mostly) align with the Guild branding guide.

### favicon

We should always use the Learners Guild icon for favicons for all services. This was a Q1 goal of "internal brand matching external brand".

**Side-note:** Please don't create new iconography in any of our services!

#### Details

The "right" way to do it (that works on all devices in a seamless way) is to do something like IDM does by downloading the `<head>` metadata as necessary from `brand.learnersguild.org`.

Check out `npm run icons:fetch` on IDM.
### Tasks

- [x] use standard favicon
- [x] ensure colors match style guide

**Comment by deadlyicon** [comment] 2017-07-10 21:36
is this a duplicate of issue https://github.com/GuildCrafts/curriculum/issues/74

**Comment by tannerwelsh** [comment] 2017-07-11 13:17
Yup. I just merged #74 into this one and will close #74.

**Comment by tannerwelsh** [comment] 2017-07-11 22:27
Ok so a first pass is ready for review here: https://github.com/GuildCrafts/curriculum/pull/91.

It's not perfect, but I didn't want to spend too much time customizing the bootflat styles if we will be merging curriculum soon anyway.

**Comment by deadlyicon** [comment] 2017-07-12 16:45
@jeffreywescott why do we have to use the standard favicon. That seems like form over function. I want to be able to distinguish between tabs more easily.

**Comment by jeffreywescott** [comment] 2017-07-12 16:59
Iif we had an "on brand" favicon that clearly communicated Learners Guild while also communicating the specific app, we would consider it. But brand trumps ugly icons in this case.

**Comment by deadlyicon** [comment] 2017-07-12 17:14
who decides what is ugly?

**Closed** 2017-07-12 19:00 UTC
